import { readFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";

/**
 * The flat search index.
 *
 * Search has to see every ranked developer, but the snapshot stores them across
 * 88 country files and 119 city files. Reading all of those on every cold start
 * would make the first API call pay for the whole dataset, so `pnpm build:index`
 * flattens them into one file that loads in a single read.
 *
 * Generated by scripts/build-index.ts, which runs as `prebuild`.
 */

export const searchRowSchema = z.object({
  login: z.string(),
  name: z.string().nullable(),
  avatarUrl: z.string(),
  company: z.string().nullable(),
  location: z.string().nullable(),
  followers: z.number().int().nonnegative(),
  total: z.number().int().nonnegative(),
  public: z.number().int().nonnegative(),
  private: z.number().int().nonnegative(),
  countryId: z.string().nullable(),
  cityId: z.string().nullable(),
  worldwideRank: z.number().int().nullable(),
  countryRank: z.number().int().nullable(),
  cityRank: z.number().int().nullable(),
  hasProfile: z.boolean(),
});

export const searchIndexSchema = z.object({
  generatedAt: z.string(),
  rows: z.array(searchRowSchema),
});

export type SearchRow = z.infer<typeof searchRowSchema>;

let cached: SearchRow[] | null = null;

export async function loadSearchIndex(): Promise<SearchRow[]> {
  if (cached) return cached;

  const file = path.join(process.cwd(), "data", "index", "search.json");
  let raw: string;
  try {
    raw = await readFile(file, "utf8");
  } catch {
    throw new Error(
      "data/index/search.json is missing. Run `pnpm build:index` (it runs automatically as " +
        "prebuild) after seeding or crawling.",
    );
  }

  const parsed = searchIndexSchema.safeParse(JSON.parse(raw));
  if (!parsed.success) {
    throw new Error(`data/index/search.json does not match its schema:\n${z.prettifyError(parsed.error)}`);
  }

  cached = parsed.data.rows;
  return cached;
}
