import { readFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";

/**
 * The flat search index.
 *
 * Search has to see every ranked developer, but the snapshot stores them across
 * 88 country files and 119 city files. Reading all of those on every cold start
 * would make the first API call pay for the whole dataset, so `pnpm build:index`
 * flattens them into one file that loads in a single read.
 *
 * ## Why tuples rather than objects
 *
 * The first version of this file stored one JSON object per developer and cost
 * **377 bytes a row** — 2.5 MB for 6,551 developers. The corpus is heading for
 * 250,000, where that same shape is 94 MB: too large to commit, too large to
 * ship inside a serverless function, and too slow to parse on a cold start.
 *
 * Two changes fix it without losing a field:
 *
 * 1. **Rows are arrays.** Object keys are the majority of the bytes when the
 *    same seventeen names repeat a quarter of a million times.
 * 2. **The avatar is a numeric account id.** A stored URL is ~90 bytes;
 *    `1006477` is seven, and {@link avatarUrlFor} rebuilds the URL exactly.
 *
 * `searchRowSchema` stays the authority on what a row *means* — the tuple is
 * purely a transport format, decoded back into that shape by {@link IndexTable}.
 *
 * ## Why an accessor table rather than an array of rows
 *
 * Materialising 250,000 objects to answer one search would hold ~100 MB of heap
 * for the sake of returning fifty rows. The table exposes per-column accessors
 * so filtering and sorting read the tuples in place, and only the page actually
 * returned is turned into {@link SearchRow} objects.
 *
 * Generated by scripts/build-index.ts, which runs as `prebuild`.
 */

/** Rebuilds the avatar URL from the numeric account id.
 *
 *  `github.com/{login}.png` is the fallback when the id is unknown: it is a
 *  real, permanent GitHub endpoint, but it is a redirect rather than a direct
 *  CDN hit, so the id is worth keeping wherever we have one. */
export function avatarUrlFor(accountId: number, login: string, size = 160): string {
  return accountId > 0
    ? `https://avatars.githubusercontent.com/u/${accountId}?s=${size}&v=4`
    : `https://github.com/${login}.png?size=${size}`;
}

export const searchRowSchema = z.object({
  login: z.string(),
  name: z.string().nullable(),
  /** GitHub's numeric account id; 0 when the snapshot does not carry one. */
  accountId: z.number().int().nonnegative(),
  avatarUrl: z.string(),
  company: z.string().nullable(),
  location: z.string().nullable(),
  followers: z.number().int().nonnegative(),
  total: z.number().int().nonnegative(),
  public: z.number().int().nonnegative(),
  private: z.number().int().nonnegative(),
  countryId: z.string().nullable(),
  cityId: z.string().nullable(),
  worldwideRank: z.number().int().nullable(),
  countryRank: z.number().int().nullable(),
  cityRank: z.number().int().nullable(),
  previousRank: z.number().int().nullable(),
  hasProfile: z.boolean(),
  streak: z.object({ current: z.number().int(), longest: z.number().int() }),
  /**
   * False when the streak was derived from a *deterministic estimate* of the
   * contribution calendar rather than a fetched one. Every surface that ranks
   * or displays a streak has to carry this through — the project's rule is that
   * an estimate is never presented as a measurement.
   */
  calendarMeasured: z.boolean(),
});

export type SearchRow = z.infer<typeof searchRowSchema>;

/* --------------------------------------------------------------- transport */

/** Bit flags packed into tuple slot {@link F.FLAGS}. */
export const HAS_PROFILE = 1;
export const CALENDAR_MEASURED = 2;

/** Tuple slot names. Written by scripts/build-index.ts, read here — changing
 *  either without the other is the one way this format can rot, so both sides
 *  import these constants rather than counting positions. */
export const F = {
  LOGIN: 0,
  ACCOUNT_ID: 1,
  NAME: 2,
  COMPANY: 3,
  LOCATION: 4,
  FOLLOWERS: 5,
  TOTAL: 6,
  PUBLIC: 7,
  COUNTRY: 8,
  CITY: 9,
  WORLDWIDE_RANK: 10,
  COUNTRY_RANK: 11,
  CITY_RANK: 12,
  PREVIOUS_RANK: 13,
  FLAGS: 14,
  STREAK_CURRENT: 15,
  STREAK_LONGEST: 16,
} as const;

export const TUPLE_LENGTH = 17;

/** A row on the wire. Strings use `""` for null and integers use `0`/`-1`, so
 *  the file never spends five bytes writing `null` a million times. */
export type RowTuple = [
  login: string,
  accountId: number,
  name: string,
  company: string,
  location: string,
  followers: number,
  total: number,
  publicContributions: number,
  countryIndex: number,
  cityIndex: number,
  worldwideRank: number,
  countryRank: number,
  cityRank: number,
  previousRank: number,
  flags: number,
  streakCurrent: number,
  streakLongest: number,
];

/**
 * Deliberately loose: this validates the *envelope*, not every one of a quarter
 * of a million rows. Running `searchRowSchema` over 250,000 decoded objects on
 * every cold start would cost more than reading the file did. The build is the
 * place that guarantees row shape, and it does so through that same schema.
 */
const indexFileSchema = z.object({
  generatedAt: z.string(),
  countries: z.array(z.string()),
  cities: z.array(z.string()),
  rows: z.array(z.array(z.union([z.string(), z.number()]))),
});

export interface IndexTable {
  generatedAt: string;
  count: number;

  /** Decodes one tuple into a full row. Call this for a page, not a corpus. */
  rowAt(index: number): SearchRow;

  loginAt(index: number): string;
  nameAt(index: number): string;
  companyAt(index: number): string;
  locationAt(index: number): string;
  followersAt(index: number): number;
  totalAt(index: number): number;
  countryAt(index: number): string | null;
  cityAt(index: number): string | null;
  hasProfileAt(index: number): boolean;
  calendarMeasuredAt(index: number): boolean;
  streakLongestAt(index: number): number;
  worldwideRankAt(index: number): number | null;

  /** Row index for a login, case-insensitively. -1 when absent. */
  indexOf(login: string): number;
}

function tableFrom(file: z.infer<typeof indexFileSchema>): IndexTable {
  const rows = file.rows as unknown as RowTuple[];
  const { countries, cities } = file;

  // Built once per process, not per query: `getDeveloper` is a point lookup and
  // scanning 250,000 logins for each one is the difference between a lookup and
  // a table scan.
  let byLogin: Map<string, number> | null = null;

  const nullable = (value: number): number | null => (value > 0 ? value : null);

  return {
    generatedAt: file.generatedAt,
    count: rows.length,

    loginAt: (i) => rows[i][F.LOGIN],
    nameAt: (i) => rows[i][F.NAME],
    companyAt: (i) => rows[i][F.COMPANY],
    locationAt: (i) => rows[i][F.LOCATION],
    followersAt: (i) => rows[i][F.FOLLOWERS],
    totalAt: (i) => rows[i][F.TOTAL],
    countryAt: (i) => countries[rows[i][F.COUNTRY]] ?? null,
    cityAt: (i) => cities[rows[i][F.CITY]] ?? null,
    hasProfileAt: (i) => (rows[i][F.FLAGS] & HAS_PROFILE) !== 0,
    calendarMeasuredAt: (i) => (rows[i][F.FLAGS] & CALENDAR_MEASURED) !== 0,
    streakLongestAt: (i) => rows[i][F.STREAK_LONGEST],
    worldwideRankAt: (i) => nullable(rows[i][F.WORLDWIDE_RANK]),

    rowAt(i) {
      const row = rows[i];
      const login = row[F.LOGIN];
      const accountId = row[F.ACCOUNT_ID];
      const total = row[F.TOTAL];
      const publicContributions = row[F.PUBLIC];

      return {
        login,
        accountId,
        avatarUrl: avatarUrlFor(accountId, login),
        name: row[F.NAME] || null,
        company: row[F.COMPANY] || null,
        location: row[F.LOCATION] || null,
        followers: row[F.FOLLOWERS],
        total,
        public: publicContributions,
        // Stored as a difference rather than a field: it is always exactly this,
        // and a quarter of a million redundant integers is not free.
        private: Math.max(0, total - publicContributions),
        countryId: countries[row[F.COUNTRY]] ?? null,
        cityId: cities[row[F.CITY]] ?? null,
        worldwideRank: nullable(row[F.WORLDWIDE_RANK]),
        countryRank: nullable(row[F.COUNTRY_RANK]),
        cityRank: nullable(row[F.CITY_RANK]),
        previousRank: nullable(row[F.PREVIOUS_RANK]),
        hasProfile: (row[F.FLAGS] & HAS_PROFILE) !== 0,
        streak: { current: row[F.STREAK_CURRENT], longest: row[F.STREAK_LONGEST] },
        calendarMeasured: (row[F.FLAGS] & CALENDAR_MEASURED) !== 0,
      };
    },

    indexOf(login) {
      if (!byLogin) {
        byLogin = new Map();
        for (let i = 0; i < rows.length; i++) byLogin.set(rows[i][F.LOGIN].toLowerCase(), i);
      }
      return byLogin.get(login.trim().toLowerCase().replace(/^@/, "")) ?? -1;
    },
  };
}

/* ----------------------------------------------------------------- loading */

const DATA_DIR = path.join(process.cwd(), "data");

let cachedTable: IndexTable | null = null;

async function readIndexFile<T>(file: string, schema: z.ZodType<T>, hint: string): Promise<T> {
  let raw: string;
  try {
    raw = await readFile(path.join(DATA_DIR, "index", file), "utf8");
  } catch {
    throw new Error(
      `data/index/${file} is missing. Run \`pnpm build:index\` (it runs automatically as ` +
        `prebuild) after seeding or crawling.${hint}`,
    );
  }

  const parsed = schema.safeParse(JSON.parse(raw));
  if (!parsed.success) {
    throw new Error(
      `data/index/${file} does not match its schema:\n${z.prettifyError(parsed.error)}`,
    );
  }
  return parsed.data;
}

export async function loadIndexTable(): Promise<IndexTable> {
  if (cachedTable) return cachedTable;
  cachedTable = tableFrom(await readIndexFile("search.json", indexFileSchema, ""));
  return cachedTable;
}

/* ------------------------------------------------------------------ orders */

export const SORTS = ["contributions", "followers", "streak"] as const;
export type Sort = (typeof SORTS)[number];

export function isSort(value: string): value is Sort {
  return (SORTS as readonly string[]).includes(value);
}

const orderFileSchema = z.object({
  generatedAt: z.string(),
  contributions: z.array(z.number().int().nonnegative()),
  followers: z.array(z.number().int().nonnegative()),
  streak: z.array(z.number().int().nonnegative()),
});

export type IndexOrder = Omit<z.infer<typeof orderFileSchema>, "generatedAt">;

let cachedOrder: IndexOrder | null = null;

/**
 * Precomputed row orderings, one per sort.
 *
 * Sorting a quarter of a million rows to serve page one is work the build has
 * already done. These are arrays of row indices, so an ordering costs about
 * 1.7 MB rather than a second copy of the corpus.
 */
export async function loadIndexOrder(): Promise<IndexOrder> {
  if (cachedOrder) return cachedOrder;
  const file = await readIndexFile(
    "order.json",
    orderFileSchema,
    " It is written alongside search.json by the same script.",
  );
  cachedOrder = {
    contributions: file.contributions,
    followers: file.followers,
    streak: file.streak,
  };
  return cachedOrder;
}
